permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 12
comments: true
paginate_path: "/blog/page/:num/"

gems:
  - jekyll-paginate

baseurl: null
domain_name: srinikusunam.com
google_analytics:

source:      source
destination: _site

itemtype: WebPage
cover: /assets/images/facebook.png

# site title, description, keywords
name: Srini Kusunam
title: Srini Kusunam • Frontend Developer / Architect
bio: "Frontend Developer, Responsive Design, Javascript, AngularJS, Baackbone, HTML5 and CSS3, "
description: "Desenvolvedor Front-end, Design Responsivo, HTML5, CSS3 e JavaScript"
keywords: "site, website, wordpress, frontend, front-end, html, html5, css, css3, js, javascript, jquery, seo, otimizacao, performance"
url: http://www.srinikusunam.com/
repo: http://github.com/skusunam/skusunam.github.io
disqus_shortname: "srinikusunam"
rss_path: source/
author:
  name      : Srini Kusunam
  image     : /assets/images/author.jpg
  email     : skusunam@libertyleap.com
  url       : http://srinikusunam.com
  # facebook  : http://facebook.com/fernando.dev
  twitter   : http://twitter.com/skusunam
  # instagram : http://instagram.com/nandomoreira.me
  github    : http://github.com/skusunam
  linkedin  : http://linkedin.com/in/skusunam
  bio       : "Founder of LibertyLEAP, frontend Architect at Moneygram. Javascript, Angular, Backbone and meetup organizer and speaker."


# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
